# name: validate-rdf
# on: [push]
# jobs:
#   setup:
#     runs-on: ubuntu-latest
#     outputs:
#       matrix: ${{ steps.ttl.outputs.paths }}
#     steps:
#       - name: checkout repo
#         uses: actions/checkout@v3
#       - name: Get all Turtle files
#         id: ttl
#         uses: Rishabh510/Path-lister-action@master
#         with:
#           path: "."
#           type: ".ttl"
#       - name: Output results
#         run: |
#           echo "Found ${{ steps.ttl.outputs.path_count }} file(s) with this extension:"
#           echo ${{ steps.ttl.outputs.paths }}
#           # for i in ${{ steps.ttl.outputs.paths }}; do
#           # echo $i
#           # done

#   validate-all-rdf-files:
#     runs-on: ubuntu-latest
#     needs:  setup
#     strategy:
#       fail-fast: false
#       matrix:
#         value: ${{ fromJson(needs.setup.outputs.matrix) }}
#     steps:
#       - uses: vemonet/jena-riot-action@v3.14
#         with:
#           input: "${{ matrix.value }}"


name: validate-rdf
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: [${{ steps.ttl.outputs.paths }}]
    steps:
      - name: Get all Turtle files
        id: ttl
        run:  echo "FILES=$(find . -name "*.ttl" -type f -exec printf "'%s',\n" {} + | sed ':a;N;$!ba;s/\n/ /g' | sed 's/,$//' | sed 's/^/[/;s/$/]/')" >> $GITHUB_ENV
      - name: Test Get file
        run: echo ${{ env.FILES }}
      # - name: Get all Turtle files
      #   id: ttl
      #   uses: Rishabh510/Path-lister-action@master
      #   with:
      #     path: "."
      #     type: ".ttl"
      # - name: Output results
      #   run: |
      #     echo "Found ${{ steps.ttl.outputs.path_count }} file(s) with this extension:"
      #     echo ${{ steps.ttl.outputs.paths }}
      #     # for i in ${{ steps.ttl.outputs.paths }}; do
      #     # echo $i
      #     # done

  validate-all-rdf-files:
    runs-on: ubuntu-latest
    needs:  setup
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # value: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Test Get file
        run: echo ${{ env.FILES }}
      - name: checkout repo
        uses: actions/checkout@v3
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: "${{ matrix.value }}"