

name: validate-rdf
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.FILES }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Get all Turtle files
        id: ttl
        run:  echo "FILES=$(find . -name "*.ttl" -type f -exec printf "'%s',\n" {} + | sed ':a;N;$!ba;s/\n/ /g' | sed 's/,$//' | sed 's/^/[/;s/$/]/')" >> $GITHUB_ENV
      - name: Test Get file
        run: echo ${{ env.FILES }}

  validate-all-rdf-files:
    runs-on: ubuntu-latest
    needs:  setup
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: "${{ matrix.value }}"