name: validate-rdf
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.ttl.outputs.paths }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Get all Turtle files
        id: ttl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "."
          type: ".ttl"

  validate-all-rdf-files:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: |
            "${{ matrix.value }}"