name: validate-rdf
on: [push]
jobs:
  validate-all-rdf-files:
    runs-on: ubuntu-latest
    steps:
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: description/description.rdfs.ttl